//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmplManagementSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Employee_Management_SystemEntities3 : DbContext
    {
        public Employee_Management_SystemEntities3()
            : base("name=Employee_Management_SystemEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<dtlForAdmin> dtlForAdmins { get; set; }
        public virtual DbSet<dtlForEmpl> dtlForEmpls { get; set; }
        public virtual DbSet<dtlForHR> dtlForHRs { get; set; }
        public virtual DbSet<dtlForManager> dtlForManagers { get; set; }
        public virtual DbSet<employeeDetail> employeeDetails { get; set; }
    
        public virtual ObjectResult<DepartmentWiseEmployeeReport_Result> DepartmentWiseEmployeeReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DepartmentWiseEmployeeReport_Result>("DepartmentWiseEmployeeReport");
        }
    
        public virtual ObjectResult<EmployeeOverview_Result> EmployeeOverview()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeOverview_Result>("EmployeeOverview");
        }
    
        public virtual ObjectResult<GetEmployeePerformanceReportByDepartment_Result> GetEmployeePerformanceReportByDepartment(string deptName, string status)
        {
            var deptNameParameter = deptName != null ?
                new ObjectParameter("deptName", deptName) :
                new ObjectParameter("deptName", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeePerformanceReportByDepartment_Result>("GetEmployeePerformanceReportByDepartment", deptNameParameter, statusParameter);
        }
    
        public virtual ObjectResult<GetEmployeeTaskReport_Result> GetEmployeeTaskReport(Nullable<int> empId)
        {
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("empId", empId) :
                new ObjectParameter("empId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeTaskReport_Result>("GetEmployeeTaskReport", empIdParameter);
        }
    
        public virtual ObjectResult<GetSalaryReport_Result> GetSalaryReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSalaryReport_Result>("GetSalaryReport");
        }
    
        public virtual ObjectResult<Pr_DepartmentHeadCount_Result> Pr_DepartmentHeadCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_DepartmentHeadCount_Result>("Pr_DepartmentHeadCount");
        }
    
        public virtual ObjectResult<Pr_DepartmentSalaryDistribution_Result> Pr_DepartmentSalaryDistribution()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_DepartmentSalaryDistribution_Result>("Pr_DepartmentSalaryDistribution");
        }
    
        public virtual ObjectResult<Pr_EmplDetailsDeptWise_Result> Pr_EmplDetailsDeptWise(string deptName)
        {
            var deptNameParameter = deptName != null ?
                new ObjectParameter("deptName", deptName) :
                new ObjectParameter("deptName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_EmplDetailsDeptWise_Result>("Pr_EmplDetailsDeptWise", deptNameParameter);
        }
    
        public virtual ObjectResult<Pr_PayrollReport_Result> Pr_PayrollReport(Nullable<int> departmentId, Nullable<bool> includeInactive)
        {
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var includeInactiveParameter = includeInactive.HasValue ?
                new ObjectParameter("IncludeInactive", includeInactive) :
                new ObjectParameter("IncludeInactive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_PayrollReport_Result>("Pr_PayrollReport", departmentIdParameter, includeInactiveParameter);
        }
    
        public virtual ObjectResult<Pr_PayrollReport1_Result> Pr_PayrollReport1(Nullable<int> departmentId, Nullable<bool> includeInactive)
        {
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var includeInactiveParameter = includeInactive.HasValue ?
                new ObjectParameter("IncludeInactive", includeInactive) :
                new ObjectParameter("IncludeInactive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_PayrollReport1_Result>("Pr_PayrollReport1", departmentIdParameter, includeInactiveParameter);
        }
    
        public virtual ObjectResult<Pr_SalaryReport_Result> Pr_SalaryReport(Nullable<decimal> minSalary, Nullable<decimal> maxSalary, string filterType)
        {
            var minSalaryParameter = minSalary.HasValue ?
                new ObjectParameter("MinSalary", minSalary) :
                new ObjectParameter("MinSalary", typeof(decimal));
    
            var maxSalaryParameter = maxSalary.HasValue ?
                new ObjectParameter("MaxSalary", maxSalary) :
                new ObjectParameter("MaxSalary", typeof(decimal));
    
            var filterTypeParameter = filterType != null ?
                new ObjectParameter("FilterType", filterType) :
                new ObjectParameter("FilterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_SalaryReport_Result>("Pr_SalaryReport", minSalaryParameter, maxSalaryParameter, filterTypeParameter);
        }
    
        public virtual ObjectResult<TaskCompletionDetailsEmpl_Result> TaskCompletionDetailsEmpl(string empName)
        {
            var empNameParameter = empName != null ?
                new ObjectParameter("empName", empName) :
                new ObjectParameter("empName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TaskCompletionDetailsEmpl_Result>("TaskCompletionDetailsEmpl", empNameParameter);
        }
    
        public virtual ObjectResult<TaskCompletionStatusReport_Result> TaskCompletionStatusReport(string status)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TaskCompletionStatusReport_Result>("TaskCompletionStatusReport", statusParameter);
        }
    
        public virtual ObjectResult<Pr_DepartmentPendingTasks_Result> Pr_DepartmentPendingTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_DepartmentPendingTasks_Result>("Pr_DepartmentPendingTasks");
        }
    
        public virtual ObjectResult<Pr_DepartmentSalaryBudget_Result> Pr_DepartmentSalaryBudget()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_DepartmentSalaryBudget_Result>("Pr_DepartmentSalaryBudget");
        }
    
        public virtual ObjectResult<Pr_DepartmentSalaryDistribution1_Result> Pr_DepartmentSalaryDistribution1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_DepartmentSalaryDistribution1_Result>("Pr_DepartmentSalaryDistribution1");
        }
    
        public virtual ObjectResult<Pr_DepartmentWiseEmployeeReport_Result> Pr_DepartmentWiseEmployeeReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_DepartmentWiseEmployeeReport_Result>("Pr_DepartmentWiseEmployeeReport");
        }
    
        public virtual ObjectResult<Pr_EmplDetailsDeptWise1_Result> Pr_EmplDetailsDeptWise1(string deptName)
        {
            var deptNameParameter = deptName != null ?
                new ObjectParameter("deptName", deptName) :
                new ObjectParameter("deptName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_EmplDetailsDeptWise1_Result>("Pr_EmplDetailsDeptWise1", deptNameParameter);
        }
    
        public virtual ObjectResult<Pr_EmployeeOverview_Result> Pr_EmployeeOverview()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_EmployeeOverview_Result>("Pr_EmployeeOverview");
        }
    
        public virtual ObjectResult<Pr_EmployeeRoleDistribution_Result> Pr_EmployeeRoleDistribution()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_EmployeeRoleDistribution_Result>("Pr_EmployeeRoleDistribution");
        }
    
        public virtual ObjectResult<Pr_GetEmployeePerformanceReportByDepartment_Result> Pr_GetEmployeePerformanceReportByDepartment(string deptName, string status)
        {
            var deptNameParameter = deptName != null ?
                new ObjectParameter("deptName", deptName) :
                new ObjectParameter("deptName", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_GetEmployeePerformanceReportByDepartment_Result>("Pr_GetEmployeePerformanceReportByDepartment", deptNameParameter, statusParameter);
        }
    
        public virtual ObjectResult<Pr_GetEmployeeTaskReport_Result> Pr_GetEmployeeTaskReport(Nullable<int> empId)
        {
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("empId", empId) :
                new ObjectParameter("empId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_GetEmployeeTaskReport_Result>("Pr_GetEmployeeTaskReport", empIdParameter);
        }
    
        public virtual ObjectResult<Pr_GetSalaryReport_Result> Pr_GetSalaryReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_GetSalaryReport_Result>("Pr_GetSalaryReport");
        }
    
        public virtual int Pr_ResignedEmployeeContribution()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_ResignedEmployeeContribution");
        }
    
        public virtual ObjectResult<Pr_TaskCompletionStatusReport_Result> Pr_TaskCompletionStatusReport(string status)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_TaskCompletionStatusReport_Result>("Pr_TaskCompletionStatusReport", statusParameter);
        }
    
        public virtual ObjectResult<Pr_TopPerformers_Result> Pr_TopPerformers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_TopPerformers_Result>("Pr_TopPerformers");
        }
    
        public virtual ObjectResult<Pr_DepartmentHeadCount1_Result> Pr_DepartmentHeadCount1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_DepartmentHeadCount1_Result>("Pr_DepartmentHeadCount1");
        }
    
        public virtual ObjectResult<Pr_Resigned_Result> Pr_Resigned()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Resigned_Result>("Pr_Resigned");
        }
    }
}
