//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmplManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int userId { get; set; }
        public int empId { get; set; }
        public string userName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string address { get; set; }
        public byte[] password { get; set; }
        public Nullable<int> roleId { get; set; }
        public bool isActive { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Role Role { get; set; }
    }
}
